[package]
name = "corvid_debug"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.15.0", optional = true }
bevy_egui = { version = "0.31.1", optional = true }
egui = { version = "0.30.0" }

[features]
default = ["bevy_engine"]
bevy_engine = ["dep:bevy", "dep:bevy_egui"]