name: Nix Package
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@14344b39ca74ae462b171571696461d555318cc3
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Test entering development environment
      run: nix develop